spring:
  data:
    mongodb:
       uri: mongodb+srv://allba:1111@cluster0.ktr3yfc.mongodb.net/?retryWrites=true&w=majority
       database: allba
debug: true
logging:
  level:
    org:
      springframework:
        context: DEBUG
        boot:
          autoconfigure: ERROR
server:
  port: 9090
